<?php
// module/Film/view/Film/Film/add.phtml:

$title = 'Ajouter un Film';
$this->headTitle($title);

$form->setAttribute('action', $this->url('Film', array('action' => 'add')));
$form->prepare();

$form->get('name')->setAttribute('class', 'mdl-textfield__input');
$form->get('name')->setAttribute('id', 'name');

$form->get('kind')->setAttribute('class', 'mdl-textfield__input');
$form->get('kind')->setAttribute('id', 'kind');

$form->get('release_year')->setAttribute('class', 'mdl-textfield__input');
$form->get('release_year')->setAttribute('id', 'release_year');
?>
<div class="mdl-card mdl-shadow--16dp centre_card">
    <div class="mdl-card__supporting-text">

        <?php echo $this->form()->openTag($form); ?>

        <?php echo $this->formHidden($form->get('id')); ?>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <?php echo $this->formRow($form->get('name')); ?>
            <label class="mdl-textfield__label" for="name">Nom du film :</label>
        </div>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <?php echo $this->formRow($form->get('kind')); ?>
            <label class="mdl-textfield__label" for="kind">Genre du film :</label>
        </div>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <?php echo $this->formRow($form->get('release_year')); ?>
            <label class="mdl-textfield__label" for="kind">Date de sortie du film :</label>
        </div>

        <button class="mdl-button mdl-js-button mdl-js-ripple-effect submit-button" type="submit">
            Ajouter le film
        </button>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>