<?php
// module/Film/view/Film/Film/index.phtml:

$title = 'Mes Films';
$this->headTitle($title);
?>

<div class="table-Film">

    <div class="fab">
        <a href="<?php echo $this->url('Film', array('action' => 'add')); ?>">
            <button
                class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored mdl-js-ripple-effect mdl-button--mini-fab">
                <i class="material-icons">add</i>
            </button>
        </a>
    </div>

    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
        <thead>
        <tr>
            <th class="mdl-data-table__cell--non-numeric">Nom du film</th>
            <th class="mdl-data-table__cell--non-numeric">Genre</th>
            <th class="mdl-data-table__cell--non-numeric">Date de sortie</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($Films as $Film) : ?>
            <tr>
                <td class="mdl-data-table__cell--non-numeric"><?php echo $this->escapeHtml($Film->name); ?></td>
                <td class="mdl-data-table__cell--non-numeric"><?php echo $this->escapeHtml($Film->kind); ?></td>
                <td class="mdl-data-table__cell--non-numeric"><?php echo $this->escapeHtml($Film->release_year); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>


