<?php
//module/Film/view/Film/auth/signup.phtml

if ($this->messages) {

    echo '<ul class="messages">';

    foreach ($this->messages as $message) echo '<li>' . $message . '</li>';

    echo '</ul>';
}

$form = $this->form;
$form->setAttribute('action', $this->url('auth/signup'));
$form->prepare();

$form->get('username')->setAttribute('class', 'mdl-textfield__input');
$form->get('username')->setAttribute('id', 'user');

$form->get('password')->setAttribute('class', 'mdl-textfield__input');
$form->get('password')->setAttribute('id', 'pwd');

$form->get('rememberme')->setAttribute('class', 'mdl-checkbox__input');
$form->get('rememberme')->setAttribute('id', 'checkbox');
?>
<div class="mdl-card mdl-shadow--16dp centre_card" xmlns="http://www.w3.org/1999/html">
    <div class="mdl-card__supporting-text">

        <?php echo $this->form()->openTag($form); ?>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <?php echo $this->formRow($form->get('username')); ?>
            <label class="mdl-textfield__label" for="user">Nom d'utilisateur:</label>
        </div>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <?php echo $this->formRow($form->get('password')); ?>
            <label class="mdl-textfield__label" for="pwd">Mot de passe:</label>
        </div>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <input class="mdl-textfield__input" type="password" name="confPassword" id="confPassword"> </input>
            <label class="mdl-textfield__label" for="confPassword">Mot de passe (confirmation):</label>
        </div>

        <button class="mdl-button mdl-js-button mdl-js-ripple-effect submit-button" type="submit">
            S'inscrire
        </button>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>